### ISSUE TITLE
How to commit with correct semantic versioning?

### ISSUE THREAD

**Issue by saeranv** [ladybug-tools/uwg#83]
Question for you @AntoineDao

I got a whole bunch of changes to the code I want to commit, but I'm a little confused about how to do it with proper semantic versioning.

Are we using this commitizen tool that this link references - https://blog.greenkeeper.io/introduction-to-semantic-release-33f73b117c8? Or do we just have to modify our commit messages?

S

**Comment by AntoineDao** [comment]
HI @saeranv!

The current setup uses a package called [python-semantic-release](https://python-semantic-release.readthedocs.io/en/latest/). This package reads the commits since the last release (version tag) and automatically bumps the version number and re-releases the repository according to the changes made. It works like comitzen but is implemented only when changes are committed and pushed to the master branch.

The way in which it determines how many numbers to bump it by depends on the nature of the commit, which is specified through the commit changes. The commit message is parsed like this:

```
type(scope): subject
```
Where type must be one of the following: 
| Commit message    | Release type               | Number bumped up |
|-------------------|----------------------------|--------------------|
|`docs(uwg): add documentation about uwg` | No release | 0.0.0 |
| `fix(epw): print epw with only one \n between lines` | Patch Release  | 0.0.x|
| `feat(uwg): add reserialization from UWG object` | Minor - Feature Release  | 0.x.0 |
| `perf(solar calc): switch all solar calcs to run on Mars` | Major - Breaking Release | x.0.0|

In practice all you have to do is be sure to use the format above in your commit messages. Then make your pull request and everything should deploy smoothly when you commit to master. You can add as many commits as you want before committing to master (this would be better practice than one giant commit) so that the changelog is more informative. It will also make it easier to review code in the long run I suspect.

**Comment by saeranv** [comment]
Sweet it worked! I broke the imperative only language rule at least once, but other then that everything looks good.

**Comment by AntoineDao** [comment]
Looking great @saeranv https://github.com/ladybug-tools/uwg/releases/tag/v5.2.0
